name: PACKAGE

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download apktool
      run: wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.4.1.jar -O apktool.jar

    - name: Rebuild APK
      run: java -jar apktool.jar b .

    - name: Sign APK
      run: |
        export PATH=$PATH:$ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION
        apksigner sign \
        --ks keystore.jks \
        --ks-pass env:KEY_STORE_PASSWORD \
        --key-pass env:PRIVATE_KEY_PASSWORD \
        ./dist/base.apk
      env:
        BUILD_TOOLS_VERSION: 29.0.2
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Release APK
      id: release_apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/base.apk
        asset_name: jellow.apk
        asset_content_type: application/vnd.android.package-archive
